using System;
using System.Collections;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using UnityEngine;

namespace MCPForUnity.Runtime
{
    /// <summary>
    /// One step of an input-simulation sequence: the command to run, its parameters, and how long
    /// to wait before running it.
    /// </summary>
    public class SequenceStep
    {
        /// <summary>Command name dispatched to the editor's input-simulation tool.</summary>
        public string Action;

        /// <summary>Parameters forwarded with the command.</summary>
        public JObject Params;

        /// <summary>Milliseconds to wait before this step runs.</summary>
        public int DelayMs;
    }

    /// <summary>
    /// Progress snapshot of a running input-simulation sequence, keyed by job id and read back by
    /// the editor while the sequence plays out over frames.
    /// </summary>
    public class SequenceJobState
    {
        /// <summary>Short id generated by <see cref="InputSimulationBridge.StartSequence"/>.</summary>
        public string JobId;

        /// <summary>One of <c>running</c>, <c>completed</c>, or <c>failed</c>.</summary>
        public string Status; // "running", "completed", "failed"

        /// <summary>Index of the step currently executing, or the step count once finished.</summary>
        public int CurrentStep;

        /// <summary>Number of steps in the sequence.</summary>
        public int TotalSteps;

        /// <summary>Failure detail when <see cref="Status"/> is <c>failed</c>; otherwise null.</summary>
        public string Error;
    }

    /// <summary>
    /// Runtime MonoBehaviour that executes input simulation sequences as coroutines.
    /// Singleton — auto-created on Play Mode start, survives scene loads.
    /// </summary>
    public class InputSimulationBridge : MonoBehaviour
    {
        static InputSimulationBridge _instance;

        /// <summary>
        /// The active bridge, lazily created (and marked <c>DontDestroyOnLoad</c>) if Play Mode
        /// started before the auto-create hook ran.
        /// </summary>
        public static InputSimulationBridge Instance
        {
            get
            {
                if (_instance == null) CreateInstance();
                return _instance;
            }
        }

        const float TimeoutSeconds = 60f;
        readonly Dictionary<string, SequenceJobState> _jobs = new Dictionary<string, SequenceJobState>();
        readonly Dictionary<string, Coroutine> _coroutines = new Dictionary<string, Coroutine>();

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        static void AutoCreate() => CreateInstance();

        static void CreateInstance()
        {
            if (_instance != null) return;
            var go = new GameObject("[MCP] InputSimulationBridge");
            DontDestroyOnLoad(go);
            _instance = go.AddComponent<InputSimulationBridge>();
        }

        /// <summary>
        /// Starts running a sequence as a coroutine and returns the job id the caller polls with
        /// <see cref="GetJobState"/>.
        /// </summary>
        /// <param name="steps">Steps to run in order.</param>
        /// <returns>An 8-character job id for the new sequence.</returns>
        public string StartSequence(List<SequenceStep> steps)
        {
            string jobId = Guid.NewGuid().ToString("N").Substring(0, 8);
            var state = new SequenceJobState
            {
                JobId = jobId,
                Status = "running",
                CurrentStep = 0,
                TotalSteps = steps.Count
            };
            _jobs[jobId] = state;
            _coroutines[jobId] = StartCoroutine(RunSequence(jobId, steps, state));
            return jobId;
        }

        /// <summary>
        /// Reads the current progress of a sequence.
        /// </summary>
        /// <param name="jobId">Id returned by <see cref="StartSequence"/>.</param>
        /// <returns>The live state object, or null when the id is unknown.</returns>
        public SequenceJobState GetJobState(string jobId)
        {
            _jobs.TryGetValue(jobId, out var state);
            return state;
        }

        IEnumerator RunSequence(string jobId, List<SequenceStep> steps, SequenceJobState state)
        {
            float startTime = Time.realtimeSinceStartup;

            for (int i = 0; i < steps.Count; i++)
            {
                // Timeout check
                if (Time.realtimeSinceStartup - startTime > TimeoutSeconds)
                {
                    state.Status = "failed";
                    state.Error = $"Sequence timed out after {TimeoutSeconds}s at step {i}.";
                    yield break;
                }

                state.CurrentStep = i;
                var step = steps[i];

                // Delay before action
                if (step.DelayMs > 0)
                    yield return new WaitForSeconds(step.DelayMs / 1000f);

                // Execute step via delegate — bridge Runtime→Editor assembly boundary
                try
                {
                    if (_commandInvoker != null)
                    {
                        var result = _commandInvoker("manage_input_simulation", step.Params);
                        // Check if result indicates failure
                        if (result is string s && s.StartsWith("ERROR:"))
                        {
                            state.Status = "failed";
                            state.Error = $"Step {i} ({step.Action}) failed: {s}";
                            yield break;
                        }
                    }
                }
                catch (Exception ex)
                {
                    state.Status = "failed";
                    state.Error = $"Step {i} ({step.Action}) threw: {ex.Message}";
                    yield break;
                }

                // Yield a frame between steps for input processing
                yield return null;
            }

            state.CurrentStep = steps.Count;
            state.Status = "completed";
            _coroutines.Remove(jobId);
        }

        // Delegate for Editor → Runtime command invocation
        static Func<string, JObject, object> _commandInvoker;

        /// <summary>
        /// Called by Editor code to register the command invoker delegate.
        /// This bridges the Runtime → Editor assembly boundary.
        /// </summary>
        /// <param name="invoker">Delegate the bridge calls to run a command; null clears the registration.</param>
        public static void RegisterCommandInvoker(Func<string, JObject, object> invoker)
        {
            _commandInvoker = invoker;
        }

        void OnDestroy()
        {
            if (_instance == this) _instance = null;
        }
    }
}
